### ISSUE TITLE
Not running

### ISSUE THREAD

**Issue by NVentimiglia** [olexale/OpenTokDroid#1]
I tried running your sample, and It would crash on start.

Android application is debugging.
Loaded assembly: /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Sample.dll
Loaded assembly: /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Bindings.dll
Loaded assembly: /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/System.ServiceModel.Internals.dll [External]
Loaded assembly: Mono.Android.dll
Loaded assembly: System.Core.dll
03-06 15:50:08.354 I/art     (14235): Late-enabling -Xcheck:jni
03-06 15:50:08.405 W/linker  (14235): /data/app/OpenTok.Sample-1/lib/arm/libmonodroid.so: is missing DT_SONAME will use basename as a replacement: "libmonodroid.so"
03-06 15:50:08.418 W/monodroid(14235): Using override path: /data/user/0/OpenTok.Sample/files/.**override**
03-06 15:50:08.418 W/monodroid(14235): Using override path: /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**
03-06 15:50:08.418 W/monodroid(14235): Trying to load sgen from: /data/user/0/OpenTok.Sample/files/.**override**/libmonosgen-2.0.so
03-06 15:50:08.418 W/monodroid(14235): Trying to load sgen from: /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/libmonosgen-2.0.so
03-06 15:50:08.418 W/monodroid(14235): Trying to load sgen from: /data/app/OpenTok.Sample-1/lib/arm/libmonosgen-2.0.so
03-06 15:50:08.419 W/monodroid(14235): Trying to load sgen from: /data/user/0/OpenTok.Sample/files/.**override**/links/libmonosgen-2.0.so
03-06 15:50:08.421 W/monodroid-debug(14235): Trying to initialize the debugger with options: --debugger-agent=transport=dt_socket,loglevel=0,address=127.0.0.1:8861,server=y,embedding=1
03-06 15:50:08.568 W/monodroid-debug(14235): Accepted stdout connection: 20
03-06 15:50:09.324 D/Mono    (14235): Image addref mscorlib[0xb44c2040] -> mscorlib.dll[0xb45ffc00]: 1
03-06 15:50:09.686 D/Mono    (14235): AOT module 'mscorlib.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-mscorlib.dll.so" not found
03-06 15:50:09.686 D/Mono    (14235): AOT module '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/mscorlib.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-mscorlib.dll.so" not found
03-06 15:50:09.689 D/Mono    (14235): Unloading image data-0x9c816000 [0xb4600100].
03-06 15:50:09.710 D/Mono    (14235): Assembly mscorlib[0xb44c2040] added to domain RootDomain, ref_count=1
03-06 15:50:09.730 D/Mono    (14235): Assembly Loader probing location: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Sample.dll'.
03-06 15:50:09.730 D/Mono    (14235): Image addref OpenTok.Sample[0xb44c2100] -> /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Sample.dll[0xb4608d00]: 2
03-06 15:50:09.730 D/Mono    (14235): Assembly OpenTok.Sample[0xb44c2100] added to domain RootDomain, ref_count=1
03-06 15:50:09.731 D/Mono    (14235): AOT module '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Sample.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-OpenTok.Sample.dll.so" not found
03-06 15:50:09.731 D/Mono    (14235): AOT module '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/OpenTok.Sample.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-OpenTok.Sample.dll.so" not found
03-06 15:50:09.731 D/Mono    (14235): Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Sample.dll'.
03-06 15:50:09.731 D/Mono    (14235): Config attempting to parse: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Sample.dll.config'.
03-06 15:50:09.732 D/Mono    (14235): Config attempting to parse: '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/etc/mono/assemblies/OpenTok.Sample/OpenTok.Sample.config'.
03-06 15:50:09.732 D/Mono    (14235): Assembly Loader probing location: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Bindings.dll'.
03-06 15:50:09.733 D/Mono    (14235): Image addref OpenTok.Bindings[0xb44c2640] -> /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Bindings.dll[0xb4609200]: 2
03-06 15:50:09.733 D/Mono    (14235): Assembly OpenTok.Bindings[0xb44c2640] added to domain RootDomain, ref_count=1
03-06 15:50:09.733 D/Mono    (14235): AOT module '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Bindings.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-OpenTok.Bindings.dll.so" not found
03-06 15:50:09.734 D/Mono    (14235): AOT module '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/OpenTok.Bindings.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-OpenTok.Bindings.dll.so" not found
03-06 15:50:09.734 D/Mono    (14235): Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Bindings.dll'.
03-06 15:50:09.734 D/Mono    (14235): Config attempting to parse: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/OpenTok.Bindings.dll.config'.
03-06 15:50:09.734 D/Mono    (14235): Config attempting to parse: '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/etc/mono/assemblies/OpenTok.Bindings/OpenTok.Bindings.config'.
03-06 15:50:09.734 D/Mono    (14235): Assembly Loader probing location: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/System.ServiceModel.Internals.dll'.
03-06 15:50:09.736 D/Mono    (14235): Image addref System.ServiceModel.Internals[0xb44c21c0] -> /storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/System.ServiceModel.Internals.dll[0xb4609700]: 2
03-06 15:50:09.736 D/Mono    (14235): Assembly System.ServiceModel.Internals[0xb44c21c0] added to domain RootDomain, ref_count=1
03-06 15:50:09.736 D/Mono    (14235): AOT module '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-System.ServiceModel.Internals.dll.so" not found
03-06 15:50:09.737 D/Mono    (14235): AOT module '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/System.ServiceModel.Internals.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-System.ServiceModel.Internals.dll.so" not found
03-06 15:50:09.737 D/Mono    (14235): Assembly Loader loaded assembly from location: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/System.ServiceModel.Internals.dll'.
03-06 15:50:09.737 D/Mono    (14235): Config attempting to parse: '/storage/emulated/0/Android/data/OpenTok.Sample/files/.**override**/System.ServiceModel.Internals.dll.config'.
03-06 15:50:09.737 D/Mono    (14235): Config attempting to parse: '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/etc/mono/assemblies/System.ServiceModel.Internals/System.ServiceModel.Internals.config'.
03-06 15:50:09.738 W/monodroid-gc(14235): GREF GC Threshold: 46080
03-06 15:50:09.738 D/Mono    (14235): Image addref Mono.Android[0xb44c2160] -> Mono.Android.dll[0xb4692000]: 1
03-06 15:50:09.738 D/Mono    (14235): Assembly Mono.Android[0xb44c2160] added to domain RootDomain, ref_count=1
03-06 15:50:09.739 D/Mono    (14235): AOT module 'Mono.Android.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-Mono.Android.dll.so" not found
03-06 15:50:09.739 D/Mono    (14235): AOT module '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/Mono.Android.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-Mono.Android.dll.so" not found
03-06 15:50:09.755 D/Mono    (14235): Unloading image data-0x9bc00000 [0xb4692500].
03-06 15:50:09.770 D/Mono    (14235): Assembly Ref addref Mono.Android[0xb44c2160] -> mscorlib[0xb44c2040]: 2
03-06 15:50:09.806 D/Mono    (14235): DllImport attempting to load: '__Internal'.
03-06 15:50:09.806 D/Mono    (14235): DllImport loaded library '(null)'.
03-06 15:50:09.806 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.806 D/Mono    (14235): Searching for '_monodroid_lref_log_new'.
03-06 15:50:09.806 D/Mono    (14235): Probing '_monodroid_lref_log_new'.
03-06 15:50:09.806 D/Mono    (14235): Found as '_monodroid_lref_log_new'.
03-06 15:50:09.809 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.809 D/Mono    (14235): Searching for '_monodroid_lref_log_delete'.
03-06 15:50:09.809 D/Mono    (14235): Probing '_monodroid_lref_log_delete'.
03-06 15:50:09.809 D/Mono    (14235): Found as '_monodroid_lref_log_delete'.
03-06 15:50:09.809 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.809 D/Mono    (14235): Searching for '_monodroid_gref_log_new'.
03-06 15:50:09.809 D/Mono    (14235): Probing '_monodroid_gref_log_new'.
03-06 15:50:09.809 D/Mono    (14235): Found as '_monodroid_gref_log_new'.
03-06 15:50:09.816 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.816 D/Mono    (14235): Searching for '_monodroid_get_identity_hash_code'.
03-06 15:50:09.816 D/Mono    (14235): Probing '_monodroid_get_identity_hash_code'.
03-06 15:50:09.816 D/Mono    (14235): Found as '_monodroid_get_identity_hash_code'.
03-06 15:50:09.842 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.842 D/Mono    (14235): Searching for 'monodroid_typemap_java_to_managed'.
03-06 15:50:09.842 D/Mono    (14235): Probing 'monodroid_typemap_java_to_managed'.
03-06 15:50:09.842 D/Mono    (14235): Found as 'monodroid_typemap_java_to_managed'.
03-06 15:50:09.878 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.879 D/Mono    (14235): Searching for '_monodroid_gref_log'.
03-06 15:50:09.879 D/Mono    (14235): Probing '_monodroid_gref_log'.
03-06 15:50:09.879 D/Mono    (14235): Found as '_monodroid_gref_log'.
03-06 15:50:09.892 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:09.892 D/Mono    (14235): Searching for 'monodroid_typemap_managed_to_java'.
03-06 15:50:09.892 D/Mono    (14235): Probing 'monodroid_typemap_managed_to_java'.
03-06 15:50:09.892 D/Mono    (14235): Found as 'monodroid_typemap_managed_to_java'.
03-06 15:50:09.895 D/Mono    (14235): Image addref System.Core[0xb44c2be0] -> System.Core.dll[0xb4693e00]: 1
03-06 15:50:09.895 D/Mono    (14235): Assembly System.Core[0xb44c2be0] added to domain RootDomain, ref_count=1
03-06 15:50:09.896 D/Mono    (14235): AOT module 'System.Core.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-System.Core.dll.so" not found
03-06 15:50:09.896 D/Mono    (14235): AOT module '/Users/builder/data/lanes/2692/e98e9627/source/monodroid/builds/install/mono-armv7/lib/mono/aot-cache/arm/System.Core.dll.so' not found: dlopen failed: library "/data/app/OpenTok.Sample-1/lib/arm/libaot-System.Core.dll.so" not found
03-06 15:50:09.897 D/Mono    (14235): Unloading image data-0x9c996000 [0xb4693400].
03-06 15:50:09.898 D/Mono    (14235): Assembly Ref addref Mono.Android[0xb44c2160] -> System.Core[0xb44c2be0]: 2
03-06 15:50:09.898 D/Mono    (14235): Assembly Ref addref System.Core[0xb44c2be0] -> mscorlib[0xb44c2040]: 3
03-06 15:50:10.059 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:10.059 D/Mono    (14235): Searching for '_monodroid_gref_log_delete'.
03-06 15:50:10.059 D/Mono    (14235): Probing '_monodroid_gref_log_delete'.
03-06 15:50:10.060 D/Mono    (14235): Found as '_monodroid_gref_log_delete'.
03-06 15:50:10.065 D/Mono    (14235): DllImport searching in: '__Internal' ('(null)').
03-06 15:50:10.065 D/Mono    (14235): Searching for '_monodroid_gc_wait_for_bridge_processing'.
03-06 15:50:10.065 D/Mono    (14235): Probing '_monodroid_gc_wait_for_bridge_processing'.
03-06 15:50:10.065 D/Mono    (14235): Found as '_monodroid_gc_wait_for_bridge_processing'.
03-06 15:50:10.070 D/Mono    (14235): Assembly Ref addref OpenTok.Bindings[0xb44c2640] -> mscorlib[0xb44c2040]: 4
03-06 15:50:10.070 D/Mono    (14235): Assembly Ref addref OpenTok.Bindings[0xb44c2640] -> Mono.Android[0xb44c2160]: 2
03-06 15:50:10.073 D/Mono    (14235): Assembly Ref addref OpenTok.Sample[0xb44c2100] -> Mono.Android[0xb44c2160]: 3
03-06 15:50:10.073 D/Mono    (14235): Assembly Ref addref OpenTok.Sample[0xb44c2100] -> OpenTok.Bindings[0xb44c2640]: 2
03-06 15:50:10.073 D/Mono    (14235): Assembly Ref addref OpenTok.Sample[0xb44c2100] -> mscorlib[0xb44c2040]: 5
Loaded assembly: MonoDroidConstructors [External]
03-06 15:50:10.184 I/art     (14235): Thread[1,tid=14235,Native,Thread_=0xb444a500,peer=0x732f73b0,"main"] recursive attempt to load library "/data/app/OpenTok.Sample-1/lib/arm/libopentok.so"
03-06 15:50:10.184 I/art     (14235): Thread[1,tid=14235,Native,Thread_=0xb444a500,peer=0x732f73b0,"main"] recursive attempt to load library "/data/app/OpenTok.Sample-1/lib/arm/libopentok.so"
03-06 15:50:10.199 I/opentok-session(14235): Connecting to the session. SessionID: 2_MX40NTUyMDc1Mn5-MTQ1NzI5NDQ0NDM4NH5BZmhTV0pyVXVYc0dyUU92WXpJNlk4THd-UH4 Token: T1==cGFydG5lcl9pZD00NTUyMDc1MiZzaWc9MTNmMTA0MmZkZTc1ZDgwODBhYjhkODc2YzczMTU1Zjk2OGRlNzk2Mjpyb2xlPXB1Ymxpc2hlciZzZXNzaW9uX2lkPTJfTVg0ME5UVXlNRGMxTW41LU1UUTFOekk1TkRRME5ETTROSDVCWm1oVFYwcHlWWFZZYzBkeVVVOTJXWHBKTmxrNFRIZC1VSDQmY3JlYXRlX3RpbWU9MTQ1NzMwNzAyMCZub25jZT0wLjk3MTQ1Mzk5NTk0MjE5ODgmZXhwaXJlX3RpbWU9MTQ1NzM5MzQyMA== ApiKey: 45520752
03-06 15:50:11.178 I/opentok-session(14235): Session is connected
03-06 15:50:11.195 I/opentok-session(14235): Starting a Publisher streaming to the session
03-06 15:50:11.213 E/AudioRecord(14235): AudioFlinger could not create record track, status: -1
03-06 15:50:11.216 E/AudioRecord-JNI(14235): Error creating AudioRecord instance: initialization check failed with status -1.
03-06 15:50:11.216 E/android.media.AudioRecord(14235): Error code -20 when initializing native AudioRecord object.
03-06 15:50:11.218 E/AudioRecord(14235): AudioFlinger could not create record track, status: -1
03-06 15:50:11.220 E/AudioRecord-JNI(14235): Error creating AudioRecord instance: initialization check failed with status -1.
03-06 15:50:11.220 E/android.media.AudioRecord(14235): Error code -20 when initializing native AudioRecord object.
referenceTable GDEF length=814 1
referenceTable GSUB length=11364 1
referenceTable GPOS length=47302 1
referenceTable head length=54 1
03-06 15:50:11.252 W/art     (14235): Native thread exiting without having called DetachCurrentThread (maybe it's going to use a pthread_key_create destructor?): Thread[14,tid=14264,Native,Thread_=0xaeab7000,peer=0x12c56220,"Thread-1132"]
03-06 15:50:11.252 F/art     (14235): art/runtime/thread.cc:1223] Native thread exited without calling DetachCurrentThread: Thread[14,tid=14264,Native,Thread_=0xaeab7000,peer=0x12c56220,"Thread-1132"]
03-06 15:50:11.261 E/mono-rt (14235): 
03-06 15:50:11.261 E/mono-rt (14235): Attempting native Android stacktrace:
03-06 15:50:11.261 E/mono-rt (14235): 
03-06 15:50:11.267 E/mono-rt (14235):  at +0 [0x9ae1e57c]
03-06 15:50:11.274 E/mono-rt (14235):  at +0 [0x0]
03-06 15:50:11.279 E/mono-rt (14235): 
03-06 15:50:11.279 E/mono-rt (14235): =================================================================
03-06 15:50:11.279 E/mono-rt (14235): Got a SIGSEGV while executing native code. This usually indicates
03-06 15:50:11.279 E/mono-rt (14235): a fatal error in the mono runtime or one of the native libraries 
03-06 15:50:11.279 E/mono-rt (14235): used by your application.
03-06 15:50:11.279 E/mono-rt (14235): =================================================================
03-06 15:50:11.279 E/mono-rt (14235): 
03-06 15:50:11.279 F/libc    (14235): Fatal signal 11 (SIGSEGV), code 1, fault addr 0x9c in tid 14264 (Thread-1132)

**Comment by olexale** [comment]
Hi! Thanks for this issue report. Unfortunately I can not check it right now. But just a few clarification questions:
1. Have you tried to run it in release mode?
2. Which device you are using?
Thanks!

**Comment by NVentimiglia** [comment]
I ended up using another Github project that was specific to Xamarin.Forms, it worked out of the box.
https://github.com/robjperez/XamarinOpenTok

I was using an Nvidia shield and an LG G3.
